project:
  type: website

website:
  title: "Julia Chifman"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Publications
        href: publications.qmd
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: CV
        href: cv.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

